//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RajaAgriApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RajaAgriApp.Resources.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get dealers.
        /// </summary>
        public static string ButtonGetdealers {
            get {
                return ResourceManager.GetString("ButtonGetdealers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aadhar card address:.
        /// </summary>
        public static string LabelAadharCardAddress {
            get {
                return ResourceManager.GetString("LabelAadharCardAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Download.
        /// </summary>
        public static string LabelDownload {
            get {
                return ResourceManager.GetString("LabelDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string LabelEdit {
            get {
                return ResourceManager.GetString("LabelEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Electrical shops.
        /// </summary>
        public static string LabelElectricalShops {
            get {
                return ResourceManager.GetString("LabelElectricalShops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Enter Pin code.
        /// </summary>
        public static string LabelEnterPinCode {
            get {
                return ResourceManager.GetString("LabelEnterPinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your Comments.
        /// </summary>
        public static string LabelEnterYourComments {
            get {
                return ResourceManager.GetString("LabelEnterYourComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Enter your mobile NO.
        /// </summary>
        public static string LabelEnterYourMobileNo {
            get {
                return ResourceManager.GetString("LabelEnterYourMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Enter your name.
        /// </summary>
        public static string LabelEnterYourName {
            get {
                return ResourceManager.GetString("LabelEnterYourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing request.
        /// </summary>
        public static string LabelExistingRequest {
            get {
                return ResourceManager.GetString("LabelExistingRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        public static string LabelFAQ {
            get {
                return ResourceManager.GetString("LabelFAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Invoice Copy.
        /// </summary>
        public static string LabelInvoiceCopy {
            get {
                return ResourceManager.GetString("LabelInvoiceCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly enter the OTP below.
        /// </summary>
        public static string LabelKindlyEnterTheOTPBelow {
            get {
                return ResourceManager.GetString("LabelKindlyEnterTheOTPBelow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindly enter your mobile number below to get OTP.
        /// </summary>
        public static string LabelKindlyEnterYourMobileNo {
            get {
                return ResourceManager.GetString("LabelKindlyEnterYourMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Landmark:.
        /// </summary>
        public static string LabelLandmark {
            get {
                return ResourceManager.GetString("LabelLandmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LabelLanguage {
            get {
                return ResourceManager.GetString("LabelLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location....
        /// </summary>
        public static string LabelLocation {
            get {
                return ResourceManager.GetString("LabelLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string LabelLogout {
            get {
                return ResourceManager.GetString("LabelLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string LabelNewRequest {
            get {
                return ResourceManager.GetString("LabelNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string LabelNotification {
            get {
                return ResourceManager.GetString("LabelNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order History.
        /// </summary>
        public static string LabelOrderHistory {
            get {
                return ResourceManager.GetString("LabelOrderHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OTP verified.
        /// </summary>
        public static string LabelOTPVerified {
            get {
                return ResourceManager.GetString("LabelOTPVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Product Invoice Date.
        /// </summary>
        public static string LabelProductInvoiceDate {
            get {
                return ResourceManager.GetString("LabelProductInvoiceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Product Name.
        /// </summary>
        public static string LabelProductName {
            get {
                return ResourceManager.GetString("LabelProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Registration.
        /// </summary>
        public static string LabelProductRegistration {
            get {
                return ResourceManager.GetString("LabelProductRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Serial number.
        /// </summary>
        public static string LabelProductSerialNumber {
            get {
                return ResourceManager.GetString("LabelProductSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Product Type.
        /// </summary>
        public static string LabelProductType {
            get {
                return ResourceManager.GetString("LabelProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend OTP -.
        /// </summary>
        public static string LabelResendOTP {
            get {
                return ResourceManager.GetString("LabelResendOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string LabelReview {
            get {
                return ResourceManager.GetString("LabelReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the Product.
        /// </summary>
        public static string LabelSelectTheProduct {
            get {
                return ResourceManager.GetString("LabelSelectTheProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        public static string LabelServiceRequest {
            get {
                return ResourceManager.GetString("LabelServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Product Serial number.
        /// </summary>
        public static string LabelStarProductSerialNumber {
            get {
                return ResourceManager.GetString("LabelStarProductSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful.
        /// </summary>
        public static string LabelSuccessful {
            get {
                return ResourceManager.GetString("LabelSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of problem.
        /// </summary>
        public static string LabelTypeOfProblem {
            get {
                return ResourceManager.GetString("LabelTypeOfProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Verify  (OTP).
        /// </summary>
        public static string LabelVerifyOTP {
            get {
                return ResourceManager.GetString("LabelVerifyOTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string PlaceHolderInput {
            get {
                return ResourceManager.GetString("PlaceHolderInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string PopUpTitleRegistration {
            get {
                return ResourceManager.GetString("PopUpTitleRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string TitleBack {
            get {
                return ResourceManager.GetString("TitleBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealers.
        /// </summary>
        public static string TitleDealers {
            get {
                return ResourceManager.GetString("TitleDealers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string TitleHome {
            get {
                return ResourceManager.GetString("TitleHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your App language.
        /// </summary>
        public static string TitleLanguagePage {
            get {
                return ResourceManager.GetString("TitleLanguagePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Service Request.
        /// </summary>
        public static string TitleNewServiceRequest {
            get {
                return ResourceManager.GetString("TitleNewServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Registration.
        /// </summary>
        public static string TitleProductRegistration {
            get {
                return ResourceManager.GetString("TitleProductRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Page.
        /// </summary>
        public static string TitleRegistrationPage {
            get {
                return ResourceManager.GetString("TitleRegistrationPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Request.
        /// </summary>
        public static string TitleServiceRequest {
            get {
                return ResourceManager.GetString("TitleServiceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to RAJA.
        /// </summary>
        public static string WelcomeToRAJA {
            get {
                return ResourceManager.GetString("WelcomeToRAJA", resourceCulture);
            }
        }
    }
}
